<?php $locs = $this->getTerminals(); ?>
<?php $current_terminal = $this->getCurrentTerminal(); ?>
<select name = "order[venipak_data]" id = "venipak_parcel_terminal_list" onchange="order.setVenipakData(this.value)" style = "width:100%; display: none;">
    <option value = "">Select pickup point</option>
            <?php
            $grouped_options = array();
            foreach ($locs as $loc) {
                $key = $loc->id;
                if (!isset($grouped_options[(string) $loc->city]))
                    $grouped_options[(string) $loc->city] = array();
                $grouped_options[(string) $loc->city][(string) $key] = $loc;
            }
            ksort($grouped_options);
            foreach ($grouped_options as $city => $locs) {
                echo '<optgroup label = "' . $city . '">';
                foreach ($locs as $key => $loc) {
                    echo '<option value = "' . $key . '" ' . ($key == $current_terminal ? 'selected' : '') . '>' . $loc->name . ', ' . $loc->address . ', ' . $loc->city . '</option>';
                }
                echo '</optgroup>';
            }
            ?>
        </select> 
<script>     
jQuery('#venipak_parcel_terminal_list').insertAfter(jQuery('#s_method_venipak_PICKUP_POINT').parent()).show();

</script>