<div id="venipak-call-courier-modal" style="display: none">
    <div class="message message-error" style = "margin:10px 0; display: none;"></div>
    <div class="message message-success" style = "margin:10px 0; display: none;"></div>
    <form action="<?= $block->escapeUrl($block->getFormUrl()) ?>" method="post"
          id="venipak-call-courier-form">
        <input type ="hidden" name ="venipakmanifest[id]" value =""  id = "venipak_manifest_id"/>
        <div class="admin__field w100">
            <label for="venipakorder_comment" class="admin__field-label"><?= __('Comment to courier (optional)') ?></label>
            <div class="admin__field-control">
                <input type ="text" name="venipakmanifest[comment]" value ="" id="venipakorder_comment" class="admin__control-text"/>
            </div>
        </div>
        <div class="admin__field w100">
            <label for="venipakorder_weight" class="admin__field-label"><?= __('Weight') ?></label>
            <div class="admin__field-control">
                <input type ="number" name="venipakmanifest[weight]" value ="" id="venipakorder_weight" class="admin__control-text"/>
            </div>
        </div>
        <div class="message message-warning" style = "margin:10px 0;">
            <ul class = "m-0 no-style">
                <li><?= __('Must be at least 2 hours difference between TIME FROM and TIME TO') ?></li>
                <li><?= __('Minutes should be indicated quarterly: 15, 30, 45, 00') ?></li>
            </ul>
        </div>
        <div class = "row">
            <div class ="col-m-4">
                <div class="admin__field w100">
                    <label for="venipakorder_arrival_date" class="admin__field-label"><?= __('Courier arrival date') ?></label>
                    <div class="admin__field-control">
                        <input type ="text" name="venipakmanifest[arrival_date]" value ="" id="venipakorder_arrival_date" class="admin__control-text datepicker arrival_date"/>
                    </div>
                </div>
            </div>
            <div class ="col-m-4">
                <div class="admin__field w100">
                    <label for="venipakorder_arrival_from" class="admin__field-label"><?= __('Courier arrival time (from)') ?></label>
                    <div class="admin__field-control">
                        <input type ="text" name="venipakmanifest[arrival_from]" value ="" id="venipakorder_arrival_from" class="admin__control-text datetimepicker arrival_from"/>
                    </div>
                </div>
            </div>
            <div class ="col-m-4">
                <div class="admin__field w100">
                    <label for="venipakorder_arrival_to" class="admin__field-label"><?= __('Courier arrival time (to)') ?></label>
                    <div class="admin__field-control">
                        <input type ="text" name="venipakmanifest[arrival_to]" value ="" id="venipakorder_arrival_to" class="admin__control-text datetimepicker arrival_to"/>
                    </div>
                </div>
            </div>
        </div>
        <div class="admin__field">
            <label for="venipakorder_warehouse" class="admin__field-label"><?= __('Warehouse') ?></label>
            <div class="admin__field-control w100">
                <?php 
                $warehouses = $this->getWarehouses();
                $default_warehouse_id = false; 
                $default_warehouse = $this->getDefaultWarehouse(); 
                if (!$default_warehouse_id && $default_warehouse){
                    $default_warehouse_id = $default_warehouse->getWarehouseId();
                }
                $selected = ''; 
                ?>
                <select name="venipakmanifest[warehouse]" id="venipakorder_warehouse" class="admin__control-select" data-default-warehouse = "<?= $default_warehouse_id; ?>">
                    <option value=""><?= __('Select warehouse'); ?></option>
                    <?php foreach ($warehouses as $warehouse): ?>
                        <?php if (!$selected && $default_warehouse && $default_warehouse_id == $warehouse['warehouse_id']){
                            $selected = 'selected = "selected"';
                        } ?>
                        <option value="<?= $warehouse['warehouse_id']; ?>" <?= $selected; ?>><?= $warehouse['name']; ?></option>
                    <?php endforeach; ?>
                </select>
            </div>
        </div>
        <div class="admin__field">
            <input type="button" value="<?= __('Send request') ?>"  class="action-default scalable action-save action-primary" id="venipak-call-courier-submit">
        </div>
    </form>
</div>
<script>
    require([
        'jquery',
        'mage/calendar'
    ], function ($) {
        $('#venipak-call-courier-modal .datetimepicker').timepicker({
            dateFormat: 'yy-mm-dd',
            timeFormat: 'HH:mm',
            stepMinute: 15,
            hourMax: 22,
            hourMin: 5,
            changeMonth: true,
            changeYear: true,
            showsTime: true
        });
        $('#venipak-call-courier-modal .datepicker').datepicker({
            dateFormat: 'yy-mm-dd',
            changeMonth: true,
            changeYear: true
        });
    });
</script>
<script>
    require(
            [
                'jquery',
                'Magento_Ui/js/modal/modal'
            ],
            function (
                    $,
                    modal
                    ) {
                var options = {
                    type: 'popup',
                    responsive: true,
                    innerScroll: true,
                    title: '<?= __('Call Venipak courier') ?>',
                    modalClass: 'custom-modal',
                    buttons: [{
                            text: $.mage.__('Close'),
                            class: '',
                            click: function () {
                                this.closeModal();
                            }
                        }]
                };

                var popup = modal(options, $('#venipak-call-courier-modal'));
                $(".call_courrier").click(function (e) {
                    e.preventDefault();
                    var warehouse = $(this).attr('data-warehouse');
                    var id = $(this).attr('data-id');
                    $('#venipak_manifest_id').val(id);
                    if (warehouse){
                        $('#venipakorder_warehouse').val(warehouse);
                    } else {
                        $('#venipakorder_warehouse').val($('#venipakorder_warehouse').attr('data-default-warehouse'));
                    }
                    $("#venipak-call-courier-modal").modal('openModal');
                });

                $('#venipak-call-courier-submit').click(function () {
                    $('#venipak-call-courier-form').append($('<input>', {
                        'name': 'form_key',
                        'value': window.FORM_KEY,
                        'type': 'hidden'
                    }));
                    $('#venipak-call-courier-form').submit();

                });
                
                var showError = function(text){
                    $("#venipak-call-courier-modal .message-error").html(text).fadeIn();
                };
                
                var showSuccess = function(text){
                    $("#venipak-call-courier-modal .message-success").html(text).fadeIn();
                };
                
                var hideMessages = function(){
                    $("#venipak-call-courier-modal .message-error").html('').hide();
                    $("#venipak-call-courier-modal .message-success").html('').hide();
                };
                
                $("#venipak-call-courier-form").submit(function (e) {
                    hideMessages();
                    e.preventDefault(); // avoid to execute the actual submit of the form.

                    var form = $(this);
                    var url = form.attr('action');

                    $.ajax({
                        type: "POST",
                        url: url,
                        data: form.serialize(), 
                        dataType: 'json',
                        success: function (data)
                        {
                            if (data.error !== undefined){
                                showError(data.error);
                            }
                            if (data.success !== undefined){
                                showSuccess(data.success);
                                if(manifest_idJsObject !== undefined){
                                    manifest_idJsObject.doFilter();
                                }
                            }
                        }
                    });


                });
                
                

            }

    );
</script>
